# -*- coding: utf-8 -*-

"""
worldometer.api
---------------

Implement a simplified api of worldometer.Worldometer Class.
"""

from .core import Worldometer


__w = Worldometer()


def current_world_population(): ...

def births_this_year(): ...

def births_today(): ...

def deaths_this_year(): ...

def deaths_today(): ...

def net_population_growth_this_year(): ...

def net_population_growth_today(): ...

def public_healthcare_expenditure_today(): ...

def public_education_expenditure_today(): ...

def public_military_expenditure_today(): ...

def cars_produced_this_year(): ...

def bicycles_produced_this_year(): ...

def computers_produced_this_year(): ...

def new_book_titles_published_this_year(): ...

def newspapers_circulated_today(): ...

def tv_sets_sold_worldwide_today(): ...

def cellular_phones_sold_today(): ...

def money_spent_on_videogames_today(): ...

def internet_users_in_the_world_today(): ...

def emails_sent_today(): ...

def blog_posts_written_today(): ...

def tweets_sent_today(): ...

def google_searches_today(): ...

def forest_loss_this_year(): ...

def land_lost_to_soil_erosion_this_year(): ...

def co2_emissions_this_year(): ...

def desertification_this_year(): ...

def toxic_chemicals_released_in_the_environment_this_year(): ...

def undernourished_people_in_the_world(): ...

def overweight_people_in_the_world(): ...

def obese_people_in_the_world(): ...

def people_who_died_of_hunger_today(): ...

def money_spent_for_obesity_related_diseases_in_the_usa_today(): ...

def money_spent_on_weight_loss_programs_in_the_usa_today(): ...

def water_used_this_year(): ...

def deaths_caused_by_water_related_diseases_this_year(): ...

def people_with_no_access_to_a_safe_drinking_water_source(): ...

def energy_used_today(): ...

def non_renewable_sources(): ...

def renewable_sources(): ...

def solar_energy_striking_earth_today(): ...

def oil_pumped_today(): ...

def oil_left(): ...

def days_to_the_end_of_oil(): ...

def natural_gas_left(): ...

def days_to_the_end_of_natural_gas(): ...

def coal_left(): ...

def days_to_the_end_of_coal(): ...

def communicable_disease_deaths_this_year(): ...

def seasonal_flu_deaths_this_year(): ...

def deaths_of_children_under_5_this_year(): ...

def abortions_this_year(): ...

def deaths_of_mothers_during_birth_this_year(): ...

def hiv_aids_infected_people(): ...

def deaths_caused_by_hiv_aids_this_year(): ...

def deaths_caused_by_cancer_this_year(): ...

def deaths_caused_by_malaria_this_year(): ...

def cigarettes_smoked_today(): ...

def deaths_caused_by_smoking_this_year(): ...

def deaths_caused_by_alcohol_this_year(): ...

def suicides_this_year(): ...

def money_spent_on_illegal_drugs_this_year(): ...

def road_traffic_accident_fatalities_this_year(): ...
