name: Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dep
      run: |
        python -m pip install --upgrade pip
        pip install requests-html
        pip install pandas
        pip install html5lib
        pip install pylint
        pip install sphinx
        pip install pytest

    - name: Run unittests
      run: |
        pytest --verbose
